### ISSUE TITLE
Error: The specified procedure could not be found. (process.dlopen)

### ISSUE THREAD

**Issue by David-Bedard** [HDF-NI/hdf5.node#113]
Hello!

I'm having an issue with the library.

When I try to run the quick start code example, I have the following error:

`internal/modules/cjs/loader.js:736
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified procedure could not be found.
\\?\C:\Users\david.bedard\Desktop\Tests\HDF\ReleaseTest\node_modules\hdf5\build\Release\hdf5.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:736:18)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\david.bedard-log\Desktop\Tests\HDF\ReleaseTest\node_modules\hdf5\index.js:7:25)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)`

I'm on Windows 10, node 11, latest 2.x python version, using the 0.3.5 HDF5.node release npm package and the 1.10 hdf5 dev library version. Node-gyp is installed globally. 

The command I've used to start the code example is `node index.js`

It would be very appreciated if someone could help me with this problem. 

Thanks a lot!

**Comment by redism** [comment]
In my case, I had different version of HDF5 (v12) was installed along with 1.10 hdf5. After deleting hdf5 1.12.5, it worked again.
