### ISSUE TITLE
Cannot build on windows

### ISSUE THREAD

**Issue by jacobabba** [HDF-NI/hdf5.node#30]
Hello,

I'm having an issue building on windows 7. Versions are:
npm: 3.9.5
node: 6.2.2

I have installed node-gyp globally, and installed hdf5 1.8.15-patch1 in the default directory. I also have vs2013 installed.

The first error that occurs is:
`c:\users\jabba\icpdashboard\node_modules\hdf5\src\file.h(11): fatal error C1083: Cannot open include file: 'hdf5.h': No such file or directory (..\src\h5_file.cc)[C:\Users\jabba\icpdashboard\node_modules\hdf5\build\hdf5.vcxproj]`

I'm probably missing something but I've been trying a bunch of stuff and nothing seems to work. Can someone help me, please?

Following is the whole output.

```
C:\Users\jabba\icpdashboard>npm install hdf5 --fallback-to-build

> hdf5@0.2.1 install C:\Users\jabba\icpdashboard\node_modules\hdf5
> node-pre-gyp install --fallback-to-build

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  hdf5.cc
  h5_file.cc
  h5_group.cc
  win_delay_load_hook.cc
c:\program files\microsoft sdks\windows\v7.1\include\sal_supp.h(57): warning C4005: '__useHeader' : macro redefinition (C:\Users\jabba\icpdashboard\node_module
s\node-gyp\src\win_delay_load_hook.cc) [C:\Users\jabba\icpdashboard\node_modules\hdf5\build\hdf5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\sal.h(2886) : see previous definition of '__useHeader'
c:\program files\microsoft sdks\windows\v7.1\include\specstrings_supp.h(77): warning C4005: '__on_failure' : macro redefinition (C:\Users\jabba\icpdashboard\no
de_modules\node-gyp\src\win_delay_load_hook.cc) [C:\Users\jabba\icpdashboard\node_modules\hdf5\build\hdf5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\sal.h(2896) : see previous definition of '__on_failure'
c:\program files\microsoft sdks\windows\v7.1\include\sal_supp.h(57): warning C4005: '__useHeader' : macro redefinition (..\src\hdf5.cc) [C:\Users\jabba\icpdash
board\node_modules\hdf5\build\hdf5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\sal.h(2886) : see previous definition of '__useHeader'
c:\program files\microsoft sdks\windows\v7.1\include\specstrings_supp.h(77): warning C4005: '__on_failure' : macro redefinition (..\src\hdf5.cc) [C:\Users\jabb
a\icpdashboard\node_modules\hdf5\build\hdf5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\sal.h(2896) : see previous definition of '__on_failure'
c:\program files\microsoft sdks\windows\v7.1\include\sal_supp.h(57): warning C4005: '__useHeader' : macro redefinition (..\src\h5_file.cc) [C:\Users\jabba\icpd
ashboard\node_modules\hdf5\build\hdf5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\sal.h(2886) : see previous definition of '__useHeader'
c:\program files\microsoft sdks\windows\v7.1\include\specstrings_supp.h(77): warning C4005: '__on_failure' : macro redefinition (..\src\h5_file.cc) [C:\Users\j
abba\icpdashboard\node_modules\hdf5\build\hdf5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\sal.h(2896) : see previous definition of '__on_failure'
c:\program files\microsoft sdks\windows\v7.1\include\sal_supp.h(57): warning C4005: '__useHeader' : macro redefinition (..\src\h5_group.cc) [C:\Users\jabba\icp
dashboard\node_modules\hdf5\build\hdf5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\sal.h(2886) : see previous definition of '__useHeader'
c:\program files\microsoft sdks\windows\v7.1\include\specstrings_supp.h(77): warning C4005: '__on_failure' : macro redefinition (..\src\h5_group.cc) [C:\Users\
jabba\icpdashboard\node_modules\hdf5\build\hdf5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\sal.h(2896) : see previous definition of '__on_failure'
c:\users\jabba\icpdashboard\node_modules\hdf5\src\file.h(11): fatal error C1083: Cannot open include file: 'hdf5.h': No such file or directory (..\src\h5_file.
cc) [C:\Users\jabba\icpdashboard\node_modules\hdf5\build\hdf5.vcxproj]
c:\users\jabba\icpdashboard\node_modules\hdf5\src\file.h(11): fatal error C1083: Cannot open include file: 'hdf5.h': No such file or directory (..\src\hdf5.cc)
 [C:\Users\jabba\icpdashboard\node_modules\hdf5\build\hdf5.vcxproj]
c:\users\jabba\icpdashboard\node_modules\hdf5\src\file.h(11): fatal error C1083: Cannot open include file: 'hdf5.h': No such file or directory (..\src\h5_group
.cc) [C:\Users\jabba\icpdashboard\node_modules\hdf5\build\hdf5.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\jabba\icpdashboard\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jabba\\icpdashboard\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build"
"--module=C:\\Users\\jabba\\icpdashboard\\node_modules\\hdf5\\lib\\binding\\hdf5.node" "--module_name=hdf5" "--module_path=C:\\Users\\jabba\\icpdashboard\\node_
modules\\hdf5\\lib\\binding"
gyp ERR! cwd C:\Users\jabba\icpdashboard\node_modules\hdf5
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\jabba\icpdashboard\node_modules\node-gyp\bin\node-gyp.js build --fal
lback-to-build --module=C:\Users\jabba\icpdashboard\node_modules\hdf5\lib\binding\hdf5.node --module_name=hdf5 --module_path=C:\Users\jabba\icpdashboard\node_mo
dules\hdf5\lib\binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\jabba\icpdashboard\node_modules\hdf5\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:852:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jabba\\icpdashboard\\node_modules\\hdf5\\node_modules\\node-pre-gyp\\bin\\node-pre-g
yp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\jabba\icpdashboard\node_modules\hdf5
node-pre-gyp ERR! node -v v6.2.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.11
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\jabba\icpdashboard\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\User
s\jabba\icpdashboard\node_modules\hdf5\lib\binding\hdf5.node --module_name=hdf5 --module_path=C:\Users\jabba\icpdashboard\node_modules\hdf5\lib\binding' (1)
superalarm@1.0.0 C:\Users\jabba\icpdashboard
+-- abbrev@1.0.9
+-- aproba@1.0.4
+-- fstream@1.0.10
+-- glob@7.0.4
+-- has-unicode@2.0.1
+-- npm-package-arg@4.2.0
+-- npm-user-validate@0.1.4
+-- read-package-tree@5.1.5
+-- readable-stream@2.1.4
+-- which@1.2.10
`-- wrappy@1.0.2

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN Failed to parse json
npm WARN Unexpected token '?' at 1:1
npm WARN ??t??♫►♂&?Z??}???K7?}???♂?+?[?P?J????;???1?i??V^?a???G►↕♦?{?X?u§?S`?i\??p?\l??u
npm WARN ^
npm WARN File: C:\Users\jabba\icpdashboard\node_modules\convert-source-map\package.json
npm WARN superalarm@1.0.0 license should be a valid SPDX license expression
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "hdf5" "--fallback-to-build"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! hdf5@0.2.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hdf5@0.2.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hdf5 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hdf5
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hdf5
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\jabba\icpdashboard\npm-debug.log

```

**Comment by rimmartin** [comment]
Hi, where is your native hdf5 library installed?

you'll need to set the switch --hdf5_home_win to point to the hdf5 library directory  on the
```
 npm install hdf5 --fallback-to-build --hdf5_home_win=<path to your hdf5 lib>
```

 line.

The default is C:/Software/hdf5

I'll be testing tomorrow at my work's windows box in preparation of next release.  I'll be able to help you more tomorrow

**Comment by rimmartin** [comment]
I'm working mostly with hdf5  1.8.17 and slightly older.  Haven't got 1.10.x working eve in pure c++ projects yet

**Comment by jacobabba** [comment]
I was specifying the path with the hdf5_home_win flag, but I think it perhaps wasn't working because of whitespace in the path (it was in Program Files). I moved it to c:/software/hdf5 and it worked. Thanks for your help!

**Comment by rimmartin** [comment]
Oh interesting.  I'll look for the white space issue in the future

**Comment by rimmartin** [comment]
Hi, Which compiler was being used?

**Comment by jacobabba** [comment]
It's the cl compiler with visual studio 12. I was enclosing the path with quotations when there was a whitespace if that makes a difference.

Also, I've had a few other problems while running the library in node.

I ended up building with 1.8.15 because 1.8.17 wasn't working. But I was getting this error on the command prompt when calling hdf5.File():

```
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.8.15, library is 1.8.17
      SUMMARY OF THE HDF5 CONFIGURATION
      =================================

General Information:
-------------------
                   HDF5 Version: 1.8.17
                  Configured on: 2016-05-11
                  Configured by: Visual Studio 14 2015 Win64
                 Configure mode: CMAKE 3.5.0
                    Host system: Windows-6.1.7601
              Uname information: Windows
                       Byte sex: little-endian
                      Libraries:
             Installation point: C:/Program Files/HDF_Group/HDF5/1.8.17

Compiling Options:
------------------
               Compilation Mode: RelWithDebInfo
                     C Compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
                         CFLAGS:  /DWIN32 /D_WINDOWS /W3
                      H5_CFLAGS:
                      AM_CFLAGS:
                       CPPFLAGS:
                    H5_CPPFLAGS:
                    AM_CPPFLAGS:
               Shared C Library: YES
               Static C Library: YES
  Statically Linked Executables: OFF
                        LDFLAGS:  /machine:x64
                     AM_LDFLAGS:
                Extra libraries: zlib-static;szip-static
                       Archiver:
                         Ranlib:
              Debugged Packages:
                    API Tracing: OFF

Languages:
----------
                        Fortran: ON
               Fortran Compiler: C:/Program Files (x86)/IntelSWTools/compilers_and_libraries_2016/windows/bin/intel64/ifort.exe
          Fortran 2003 Compiler: ON
                  Fortran Flags:  /W1 /nologo /fpp /libs:dll /threads
               H5 Fortran Flags:
               AM Fortran Flags:
         Shared Fortran Library: YES
         Static Fortran Library: YES

                            C++: ON
                   C++ Compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
                      C++ Flags:  /DWIN32 /D_WINDOWS /W3 /GR /EHsc
                   H5 C++ Flags:
                   AM C++ Flags:
             Shared C++ Library: YES
             Static C++ Library: YES

Features:
---------
                  Parallel HDF5: OFF
             High Level library: ON
                   Threadsafety: OFF
            Default API Mapping: v18
 With Deprecated Public Symbols: ON
         I/O filters (external):  DEFLATE DECODE ENCODE
                            MPE:
                     Direct VFD:
                        dmalloc:
Clear file buffers before write: ON
           Using memory checker: OFF
         Function Stack Tracing: OFF
      Strict File Format Checks: OFF
   Optimization Instrumentation:
Bye...
```

This error is resolved WITHOUT REBUILDING if I move the 1.8.17 directory out of c:\Program Files\hdf_group\hdf5 (only leaving the 1.8.15 directory). I guess it's trying to use the dlls of the highest version in that directory?

Also, once I move the 1.8.17 directory out, I then get a failed assertion that looks like this when calling hdf5.File: 

![error](https://cloud.githubusercontent.com/assets/11514148/17452540/d2157fa4-5b24-11e6-8b13-1b952fa19ce8.PNG)

**Comment by jacobabba** [comment]
Whoops, I was dumb and didn't include the 'new' keyword in front of hdf5.File, which solved the above error.

This might be a silly question, but how do I open the root group of a file so I can call group methods (such as getMemberNames, getDatasetAttributes, etc)? The file object has getMemberNamesByCreationOrder but doesn't have an alphabetical option. I've tried file.openGroup('/') but it just crashes.

**Comment by rimmartin** [comment]
I'll add getMemberNames and others that might be needed to the file level.  Won't take long.  Might look at treating it as a group if possible. I got attributes working that way.  Thank yofr thefeed back.

 also want to see when new isn't used if it can stop more gracefully

**Comment by rimmartin** [comment]
Hi @vincent-tr,

I moved some code around. Put Attributes implementation in a cc file and introduced a Methods class between Attributes and File & Group for common methods of both accessing info about attributes and children.   Is this okay with you?  Better way to do it?

**Comment by vincent-tr** [comment]
That sounds good :)

**Comment by rimmartin** [comment]
There is now common code between group and file for methods like getMemberNames which get information about child members
