### ISSUE TITLE
TypeError: Failed to open file {file_name} and flags 0 with return: -1.

### ISSUE THREAD

**Issue by tayabsoomro** [HDF-NI/hdf5.node#47]
I am running this following code from the index.js file in the routes of my express project.

  ```
 var express = require('express');
var hdf5 = require('hdf5').hdf5;
var router = express.Router();

var Access = require('hdf5/lib/globals').Access;
var file = new hdf5.File('filename.fast5', Access.ACC_RDONLY);
var group = file.openGroup('/Raw/Reads/Read_53');
```

I am storing the file in the same directories in which the index.js file is residing. 
Here's the tree structure of my project showing where the fast5 file is in:

```
./
├── README.md
├── app.js
├── bin
│   └── www
├── d3
│   ├── API.md
│   ├── CHANGES.md
│   ├── LICENSE
│   ├── README.md
│   ├── d3.js
│   └── d3.min.js
├── includes
│   ├── css
│   ├── data
│   └── js
├── index.html
├── node_modules
│   
|      .... 
│   ├── hdf5
|     ....
├── package.json
├── routes
│   ├── filename.fast5
│   ├── index.js
│   └── users.js
└── views
    ├── error.ejs
    └── index.ejs
```

And here's the error that I am getting:

```
╭─tayabsoomro
╰─$ npm start                                                                                                                                                1 ↵

> nanopore-data-visualizer@0.0.0 start /Volumes/Coruscant/project
> node ./bin/www

HDF5-DIAG: Error detected in HDF5 (1.10.1) thread 0:
  #000: H5F.c line 586 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1236 in H5F_open(): unable to open file: time = Fri Aug 25 10:06:39 2017
, name = 'filename.fast5', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 809 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: H5FDsec2.c line 346 in H5FD_sec2_open(): unable to open file: name = 'filename.fast5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
/Volumes/Coruscant/project/routes/index.js:6
var file = new hdf5.File('filename.fast5', Access.ACC_RDONLY);
           ^

TypeError: Failed to open file, filename.fast5 and flags 0 with return: -1.

    at TypeError (native)
    at Object.<anonymous> (/Volumes/Coruscant/project/routes/index.js:6:12)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/Coruscant/project/app.js:8:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
```

**Comment by rimmartin** [comment]
Hi, Ill try to replicate a best I can. Untl  find anything you might want to try

```
var file = new hdf5.File(__dirname+'/filename.fast5', Access.ACC_RDONLY);
```
which gives it index.js's path

**Comment by tayabsoomro** [comment]
That actually fixed it! I tried it with `./filename.fast5` which also threw the same error. I think it could be concluded from this that the function `hdf5.File()` requires an absolute path to the file.


Thank you!

**Comment by rimmartin** [comment]
Good! Nneed not be absolute; but can't gap from working directory
