### ISSUE TITLE
Syntax Error: unsupported data type

### ISSUE THREAD

**Issue by tayabsoomro** [HDF-NI/hdf5.node#48]
I am trying to retrieve a data type for a fast5 file but it throws the following error:

```
/Volumes/Coruscant/project/routes/index.js:17
var dataset = h5lt.readDataset(group.id,'Events');
                   ^
SyntaxError: unsupported data type
    at SyntaxError (native)
    at Object.<anonymous> (/Volumes/Coruscant/project/routes/ind
ex.js:17:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/Coruscant/project/app.js:8:1
3)
```

Here's how the dataset looks like in `h5dump`:

```
HDF5 "file1.fast5" {
DATASET "/Analyses/Basecall_1D_001/BaseCalled_template/Events" {
   DATATYPE  H5T_COMPOUND {
      H5T_IEEE_F32LE "mean";
      H5T_IEEE_F32LE "stdv";
      H5T_IEEE_F32LE "start";
      H5T_IEEE_F32LE "length";
      H5T_STRING {
         STRSIZE 5;
         STRPAD H5T_STR_NULLPAD;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      } "model_state";
      H5T_STD_I32LE "move";
      H5T_IEEE_F32LE "weights";
      H5T_IEEE_F32LE "p_model_state";
      H5T_STRING {
         STRSIZE 5;
         STRPAD H5T_STR_NULLPAD;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      } "mp_state";
      H5T_IEEE_F32LE "p_mp_state";
      H5T_IEEE_F32LE "p_A";
      H5T_IEEE_F32LE "p_C";
      H5T_IEEE_F32LE "p_G";
      H5T_IEEE_F32LE "p_T";
   }
   DATASPACE  SIMPLE { ( 12771 ) / ( 12771 ) }
   DATA {
   (0): {
         137.778,
         0.528982,
         218.686,
         0.001,
         "CTGTT",
         1,
         0.0343166,
         0.262244,
         "CTGTT",
         0.262244,
         0.16503,
         0.079916,
         0.679372,
         0.075683
      },
   (1): {
         110.178,
         2.62537,
         218.687,
         0.001,
         "CTGTT",
         0,
         0.420341,
         0.0162997,
         "TATTT",
         0.219776,
         0.301549,
         0.0163437,
         0.0578457,
         0.624261
      },
   ...
   .... {hidden items} ....
   ...
(12770): {
         116.651,
         5.52655,
         234.834,
         0.001,
         "TTCGC",
         0,
         1,
         0.0477271,
         "TTTAA",
         0.080599,
         0.4063,
         0.25599,
         0.16818,
         0.16953
      }
   }
}
}

**Comment by rimmartin** [comment]
At first glance it looks like it is a table instead of a dataset
http://hdf-ni.github.io/hdf5.node/ref/file.html
You can find out with  File.prototype.getDatasetType(name) or Group.prototype.getDatasetType(name) it it will bring back an enumeration from http://hdf-ni.github.io/hdf5.node/ref/globals.html#hltype

I'll look thru it some more.  but the one column is a string and the rest are doubles; probably a table.  You can also see what the type is by the hdfviewer
